version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: pomodoro-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache-test:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
